name: Build and Release on Master

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        continue-on-error: true

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Setup GitHub CLI
        uses: cli/cli-action@v3

      - name: Create Release
        run: |
          # Generate a tag with date + workflow run number
          TAG="v$(date +'%Y.%m.%d')-${GITHUB_RUN_NUMBER}"
          echo "Creating tag $TAG"
          
          # Configure git
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # Create and push the tag
          git tag $TAG
          git push origin $TAG
          
          # Create GitHub release and attach published files
          gh release create $TAG ./publish/* --title "$TAG" --notes "Automated release from GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
