name: Build and Release on Master

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        continue-on-error: true

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

      - name: Zip Publish Folder
        run: zip -r release.zip ./publish

      - name: Create Tag and Release
        run: |
          # Generate a unique tag using date + workflow run number
          TAG="v$(date +'%Y.%m.%d')-${GITHUB_RUN_NUMBER}"
          echo "Creating tag $TAG"

          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          git tag $TAG
          git push origin $TAG

          gh release create $TAG release.zip --title "$TAG" --notes "Automated release from GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
